### ISSUE TITLE
[Suggestion] Option to remove the shulker boxes enchanted books from the game.

### ISSUE THREAD

**Issue by KBeiller** [RubixDev/EnchantedShulkers#16]
Hey I really like this mod and it would really add to my modded SSP but i have this sort of rule that any mod installed should never add items/blocks to the game. This is referring to the enchanted books that could spawn in chests or in villager trades.

Obviously, this is just a suggestion im not saying that everyone seeks this but I would really like to have an option to make it "command-only" so to have these features you would need to type the command with the enchantment you want and then it would work as it does, without any new items involved. 

Thanks really much and I hope you like this suggestion c:

**Comment by RubixDev** [comment]
I can definitely have a look at how complicated that is to implement, and if it turns out to be manageable, i will add the option for sure (more options are always better :wink:). It might take a while (like two or three weeks) for me to get back to this though, as I'm currently quite busy with school :neutral_face:

**Comment by RubixDev** [comment]
The new option `generateBooks` will be available in the upcoming 1.1.2 release, which you will want to set to `false`
