### ISSUE TITLE
1.18.2 client crash with create

### ISSUE THREAD

**Issue by dadoirie** [RubixDev/EnchantedShulkers#2]
as the title says ... client crashes when loading it with create, which wasn't a problem with the alpha version
here's the log:
https://mclo.gs/Qkp6vMn

and strange enough that the server does not crash, but since this mod is required on the client and server client needs to get fixed

**Comment by RubixDev** [comment]
I don't really understand the exact cause of the crash, but I was able to rewrite the function that caused it.

> and strange enough that the server does not crash
The crash happened in the code for rendering enchanted ender chests, which obviously only exists on clients. Create apparently changes the rendering stuff quite a lot, so the enchantment glint on placed containers does not work while Create is installed, but since the functionality isn't affected and I don't have the motivation to try and fix that, this will just stay.

The fix is available in v1.0.1

**Comment by dadoirie** [comment]
thanks
