### ISSUE TITLE
[Compatibility] Duplication / deletion bug with stackable shulker boxes using AllStackable mod

### ISSUE THREAD

**Issue by chimericdream** [RubixDev/EnchantedShulkers#25]
This is on Fabric 0.14.22-1.20.1 with version 1.1.3 of EnchantedShulkers and 2.0.0 of AllStackable.

Duplication Glitch: When a stack of shulkers have the "Siphon" enchantment each time an item is siphoned into the stack it adds 1 to each of the shulkers in the stack resulting in a massive duplication. For example if I have a stack of 16 siphon shulker boxes and pick up one diamond it will dup into 16 diamonds.

Deletion Glitch: When a stack of shulkers have the "Refill" enchantment each time an item is refilled from the approprate stack it decreases by 1 each of the shulkers in that stack, resulting in a deletion of the other items. For example if I have a stack of 16 refill shulker boxes full of cobblesone and place one cobble it will place just one cobble in my inventory but all 16 shulkers will reduce by one.

**Comment by RubixDev** [comment]
Sadly, due to the nature of how the stacking is achieved, this will be impossible to make fully compatible. Even with the AllStackable mod, only shulker boxes with the same items in the same slots can be stacked, but when a siphon or refill would need to modify just _one_ of these the stack would need to be split in two. What I did now is to just ignore stacks of shulker boxes if the count isn't one. This way, no duplication or deletion occurs, but stacked shulker boxes also lose their enchantment functionality.
