### ISSUE TITLE
Add generateBooks option to older versions

### ISSUE THREAD

**Issue by KBeiller** [RubixDev/EnchantedShulkers#27]
Hey, a while back I suggested the generateBooks option wich im so thankful it got added, still, I'm currently stuck on the 1.19.2 and it would be much appreciated if you could add these features to older versions of the game. Thx

**Comment by RubixDev** [comment]
This is actually already done on the https://github.com/RubixDev/EnchantedShulkers/tree/main branch, but isn't in any release yet. The plan is to create a new release after I closed #22 and hopefully some of the incompatibility issues.

**Comment by RubixDev** [comment]
nvm sorry, I thought you meant 1.19.4 and that even already has a release with that feature. I won't do any more backporting to versions before 1.19.4 since I now make use of Minecraft features that don't exist in older versions. That could of course be worked around but I don't want to do that myself. The proper "fix" would be to get the other mods that keep you on 1.19.2 updated to a newer version.

**Comment by KBeiller** [comment]
Alr completly understandable. Thx have a great day and thank you for this amazing mod.
