### ISSUE TITLE
Augmentable chests and barrels

### ISSUE THREAD

**Issue by RubixDev** [RubixDev/EnchantedShulkers#52]
Could be nice to have options to allow barrels and chests to also be enchanted with Augment. One potential difficulty to look out for is that all other enchantable items are non-stackable, so some custom workarounds in anvils may be necessary (actually, how do I handle this with ender chests atm?). It can also be tedious for players to have to enchant chests one by one, but that may just be a part of balancing. For chests specifically there's also the question of how to handle double chests.

**Comment by RubixDev** [comment]
> One potential difficulty to look out for is that all other enchantable items are non-stackable, so some custom workarounds in anvils may be necessary (actually, how do I handle this with ender chests atm?).
The game already sets the xp levels needed to enchant stacks with a count > 1 to 40 which is "Too Expensive" in survival, so that's not a problem.

**Comment by allanonmage** [comment]
I use AllStackable in my 1.19.2 modpack to change the stacking of lots of items, some tools and armor. It's a little quirky, but the players will learn. For example, if you add a stack of enchanted books, they are all consumed in the anvil. But otherwise it's great. Differing NBT data prevents stacking, so it's usually only books and mass manufactured items you have to worry about that sort of thing.
